### ISSUE TITLE
DeepL removes semicolon from the text

### ISSUE THREAD

**Issue by niketh90** [lecode-official/deepl-dotnet#12]
When I try using the plugin to translate using deepl in dotnet, semicolons in the text are getting removed from translated text. It does work fine using postman on deepl API directly. Fails using the plugin.
Input params are given below.
```
text &lt;P2C.WA&gt;  and     &lt;P2C.WA&gt;
source_lang en
target_lang cs
preserve_formatting 1
split_sentences 1
tag_handling xml
outline_detection 1
```

`Output: &lt;P2C.WA&gt; a &lt;P2C.WA&gt
`

If I set preserve_formatting 0, it will return correct data
`&lt;P2C.WA&gt; a &lt;P2C.WA&gt; `

**Comment by lecode-official** [comment]
Hi Niketh,

sorry that I am only coming back to you, now. Can you please provide the code where you invoke the `Translate` method?

**Comment by lecode-official** [comment]
Since there has been little activity in this issue in the past few weeks, I will close it for now. If the issue persists, please reopen with more relevant information.
