### ISSUE TITLE
 Translate function parameter formality

### ISSUE THREAD

**Issue by hauffautomation** [lecode-official/deepl-dotnet#14]
Is it possible to add the parameter "formality" to the translate function?

> formality	Optional	Sets whether the translated text should lean towards formal or informal language. This feature currently only works for target languages "DE" (German), "FR" (French), "IT" (Italian), "ES" (Spanish), "NL" (Dutch), "PL" (Polish), "PT-PT", "PT-BR" (Portuguese) and "RU" (Russian).Possible options are:

    "default" (default)
    "more" - for a more formal language
    "less" - for a more informal language

**Comment by lecode-official** [comment]
Hi Paul,

sorry for the taking so long to answer. I am working on adding the formality parameter. I'll let you know when I am finished.

**Comment by lecode-official** [comment]
Hi Paul,

I just merged the formality parameter into the main branch. I will publish an updated NuGet package in a couple of minutes. Please let me know if everything works for you.

**Comment by hauffautomation** [comment]
Thank you very much David. Everything worked.

**Comment by lecode-official** [comment]
I am happy to hear that
