### ISSUE TITLE
Add languages

### ISSUE THREAD

**Issue by Martin4Kostal** [lecode-official/deepl-dotnet#17]
Dear all,
could you please the currently available languages to the Language enum?
Especially Turkish (TR), Polish (PL) and Romanian (RO) would be very helpful for us.
Thanks a lot in advance,
Martin

**Comment by lecode-official** [comment]
Hi Martin,

thank you for opening an issue. Polish and Romanian were already available in 0.4.0 (maybe you have an older version installed). But Turkish and Indonesian were missing. I just added them and published a new version to NuGet (v0.4.1). It might take a couple more minutes until the new version is indexed and visible to you. I hope this helps.

David

**Comment by Martin4Kostal** [comment]
Hi David,
thanks for the quick fix ☺
Martin
