### ISSUE TITLE
Add Ukrainian language

### ISSUE THREAD

**Issue by Martin4Kostal** [lecode-official/deepl-dotnet#19]
I just discovered that Ukrainian language is now supported as well. It would be a great support for our Ukrainian colleagues if we could provide documents in local language.

**Comment by lecode-official** [comment]
I am currently on vacation, but will have a look at it when I am back next week.

**Comment by lecode-official** [comment]
I am about to release an update to NuGet, you should be able to see it in a couple of minutes.
