### ISSUE TITLE
Unknown error at runtime

### ISSUE THREAD

**Issue by vincentagi** [lecode-official/deepl-dotnet#5]
Good morning,
Thank you for this work.
I have a little problem while running the code on visual studio.
I don't understand it very well. Especially the program crashes completely without more clue.
I give you the internal trace.
Thanks

Exception non gérée : System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'Microsoft.AspNetCore.StaticFiles, Version=2.2.0.0, Culture=neutral, PublicKeyToken=' ou une de ses dépendances. Le fichier spécifié est introuvable.
   à DeepL.DeepLClient..ctor(String authenticationKey)
   à Application.Program.<MainAsync>d__1.MoveNext() dans C:\Users\Vincent\Documents\translation Deepl\deepl-dotnet\source\DeepL\Program.cs:ligne 27
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Task.Wait()
   à Application.Program.Main(String[] arguments) dans C:\Users\Vincent\Documents\translation Deepl\deepl-dotnet\source\DeepL\Program.cs:ligne 20

**Comment by lecode-official** [comment]
Hi @vincentagi,

According to DeepL's translation, the exception message reads that the Assembly Microsoft.AspNetCore.StaticFiles, Version=2.2.0.0, or one of its dependencies could not be found. Without further information this is just a guess into the blue, but I suspect that you either reference a different version of Microsoft.AspNetCore.StaticFiles yourself or you have a reference to another package, that has a reference to a different version.

Could you please tell me what framework you are targetting (&lt;TargetFramework&gt; in your .csproj file) and a list of your dependencies (&lt;PackageReference&gt; in your  .csproj file). Maybe I can find something to reproduce your problem.

**Comment by vincentagi** [comment]
Hello,
Following your message of yesterday I looked more precisely at the target framework. It turns out that the version 2.0 dotnet and the target framework. The problem is that visual studio does not find the 4.6 that is installed.
Thanks

**Comment by lecode-official** [comment]
Hi @vincentagi,

I am happy to hear that you could resolve your problem. If you have any more problems, don't hesitate to open another issue.
