### ISSUE TITLE
DeepL terminate on translation

### ISSUE THREAD

**Issue by pepelotte** [lecode-official/deepl-dotnet#7]
Hi,

frist, thank you for your great work you´ve done. i have an issue. the program terminate with no exeption while start translating. the line where the code quit is

HttpResponseMessage responseMessage = await this.httpClient.PostAsync(
                    this.BuildUrl(DeepLClient.translatePath),
                    httpContent,
                    cancellationToken

its from this block

            // Sends a request to the DeepL API to translate the text
            using (HttpContent httpContent = new FormUrlEncodedContent(parameters))
            {
                HttpResponseMessage responseMessage = await this.httpClient.PostAsync(
                    this.BuildUrl(DeepLClient.translatePath),
                    httpContent,
                    cancellationToken
                );
                await this.CheckResponseStatusCodeAsync(responseMessage);

                // Retrieves the returned JSON and parses it into a .NET object
                string translationResultContent = await responseMessage.Content.ReadAsStringAsync();
                return JsonConvert.DeserializeObject<TranslationResult>(translationResultContent).Translations;
            }

**Comment by pepelotte** [comment]
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: DefaultDomain): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: DefaultDomain): "D:\IT Docs - pretorix\pretorix - Ecomed Import\bin\Debug\pretorix - Ecomed Import.exe" geladen. Symbole wurden geladen.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.resources\v4.0_4.0.0.0_de_b77a5c561934e089\System.Data.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.Wrapper.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "D:\IT Docs - pretorix\pretorix - Ecomed Import\bin\Debug\DeepL.dll" geladen. Symbole wurden geladen.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "D:\IT Docs - pretorix\pretorix - Ecomed Import\bin\Debug\Microsoft.AspNetCore.StaticFiles.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "D:\IT Docs - pretorix\pretorix - Ecomed Import\bin\Debug\Newtonsoft.Json.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
"pretorix - Ecomed Import.exe" (CLR v4.0.30319: pretorix - Ecomed Import.exe): "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
Das Programm "[20640] pretorix - Ecomed Import.exe" wurde mit Code 0 (0x0) beendet.

**Comment by pepelotte** [comment]
Mybe helpful ;-)

**Comment by lecode-official** [comment]
Hi @pepelotte,

thank you for opening an issue. This seems to be a tough one, I have never before had a problem that just terminated a .NET process without exception (at least not with all managed code). Can you please tell me the .NET Framework version that you are targeting? DeepL.NET is build against .NET Standard 2.0, which means you have to run at least .NET Framework 4.6.1.

**Comment by pepelotte** [comment]
I´ve tried it with .net5 and .net4.8

**Comment by pepelotte** [comment]
...and i use the newest vs studio version 16.9.4

**Comment by lecode-official** [comment]
Hi @pepelotte, I am really sorry that I am only writing back now, but I was on vacation this week and was spending some quality time with the family.

Getting back to your problem: I still can not wrap my head around this and can not for the life of me figure out what the problem could be. Unfortunately, I do not have a Windows system set up right now to test this myself. I haven't been working with Windows and Visual Studio for quite some time. I have been testing DeepL.NET using .NET Core 3.1.201. Is it possible for you to install .NET Core 3 and test your project again?

**Comment by lecode-official** [comment]
Hi @pepelotte,

I have just published a new version of DeepL.NET to NuGet. There is a bugfix in there. I am not 100% certain that this fix will solve your problem, but I we can give it a try :-)

If your problem still persists after the update, can you please try the following:

Check the build configuration of your solution. In what configuration have you built your solution? Is it a release build or a Debug build? If it was built in Release, then please build it in Debug mode, so that your assembly contains symbol information. That may give us a more complete error message.

Also, can you send me a short code snippet of how you invoke the `Translate` method? This may also help me figure out what the problem is.

**Comment by pepelotte** [comment]
Hi,
Now I have to apologise. We're super busy right now and I just don't have time to do any more tests. I hope I'll be able to do it during the week and will report back then.
Kind regards

**Comment by lecode-official** [comment]
Hi @pepelotte,

absolutely no problem, just get back at me, when you were able to do some tests. I'll keep this issue open.

**Comment by lecode-official** [comment]
Hi @pepelotte,

have you had a chance to checkout the new version? Are you still interested in this issue? If not, then I would close it, since I can not find out what I can do to fix this.

**Comment by pepelotte** [comment]
Hi David,
 
i will test it this week on a new developer pc. Maybe my computer causes the problem.
 
Regards
 
Heiko Faiss
CEO and Head of Softwaredevelopment
 
IT Docs GmbH • Zehntweg 5 • 72393 Burladingen-Melchingen
Fon: (+49) 0 74 73 – 92 40 600 • E-Mail: ***@***.*** ***@***.***
 
Von: David Neumann ***@***.***> 
Gesendet: Freitag, 25. Juni 2021 11:22
An: lecode-official/deepl-dotnet ***@***.***>
Cc: pepelotte ***@***.***>; Mention ***@***.***>
Betreff: Re: [lecode-official/deepl-dotnet] DeepL terminate on translation (#7)
 
Hi @pepelotte https://github.com/pepelotte,
have you had a chance to checkout the new version? Are you still interested in this issue? If not, then I would close it, since I can not find out what I can do to fix this.

**Comment by pepelotte** [comment]
Hi David,
 
we have now changed computers and also switched from vb.net to a c# development environment. the code runs fine there. was probably either the visualstudio environment or the vb.net code.
 
Regards
 
Heiko Faiss
CEO and Head of Softwaredevelopment
 
IT Docs GmbH • Zehntweg 5 • 72393 Burladingen-Melchingen
Fon: (+49) 0 74 73 – 92 40 600 • E-Mail: ***@***.*** ***@***.***
 
Von: David Neumann ***@***.***> 
Gesendet: Freitag, 25. Juni 2021 11:22
An: lecode-official/deepl-dotnet ***@***.***>
Cc: pepelotte ***@***.***>; Mention ***@***.***>
Betreff: Re: [lecode-official/deepl-dotnet] DeepL terminate on translation (#7)
 
Hi @pepelotte https://github.com/pepelotte,
have you had a chance to checkout the new version? Are you still interested in this issue? If not, then I would close it, since I can not find out what I can do to fix this.

**Comment by pepelotte** [comment]
we have now changed computers and also switched from vb.net to a c# development environment. the code runs fine there. was probably either the visualstudio environment or the vb.net code.

**Comment by lecode-official** [comment]
Thanks for letting me know. I am happy that everything is working now.
